"""camera關聯user_id

Revision ID: af0b14c2e267
Revises: b2afa59b7467
Create Date: 2024-09-14 12:24:37.123506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af0b14c2e267'
down_revision = 'b2afa59b7467'
branch_labels = None
depends_on = None


# migrations/versions/af0b14c2e267_camera關聯user_id.py
def upgrade():
    # 添加 user_id 並設置默認值
    with op.batch_alter_table('camera', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False, server_default='1'))  # 默認 user_id 為 1 (管理員)
    
    # 之後可以刪除 server_default，讓 user_id 必須手動設置
    op.alter_column('camera', 'user_id', server_default=None)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('camera', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
